version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000
    environment:
      - BASE_URL
      - INFURA_URL
      - CONTRACT_ADDRESS
    restart: always
    command: >
      bash -c "python manage.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    environment:
      - NODE_ENV
      - REACT_APP_OPENSEA_URL
    depends_on:
      - backend
    restart: always

  reverse_proxy:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    restart: always
