# Generated by Django 3.1.4 on 2022-06-22 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nftmetadata.models
import nftmetadata.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTMetadata',
            fields=[
                ('id', models.IntegerField(default=nftmetadata.models.NFTMetadata.increment_count, primary_key=True, serialize=False, verbose_name='Unique RitzyReso ID, used to reference the reso')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('external_url', models.URLField(blank=True, default='http://www.ritzyreso.com', null=True)),
                ('event_datetime', models.DateTimeField(null=True)),
                ('diners', models.IntegerField(null=True)),
                ('opensea_url', models.URLField(blank=True)),
                ('nft_metadata_version', models.CharField(default='.1', max_length=100)),
                ('image_file', models.ImageField(blank=True, null=True, storage=nftmetadata.storage.OverwriteStorage(), upload_to=nftmetadata.models.NFTMetadata.photo_path)),
                ('nft_network', models.CharField(default='rinkeby', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
